name: CD

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  Terraform-AWS:
    runs-on: ubuntu-latest
    environment:
      name: CD

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id:   apply
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve

        



