name: integration
on:
  push:
    branches:
      - testing

jobs:
  jobs_ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: build
        run: npm run build
      - name: test
        run: npm run test

