name: Integration
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Integration:
    runs-on: ubuntu-18.04
    environment:
      name: Integration
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: build
        run: npm run build

