name: Versions

on:
  push:
    branches: [master]
  workflow_dispatch:
      
jobs:
  Dockerizing-backend:
    runs-on: ubuntu-latest
    environment:
      name: Versions
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Create env file'
        run: |
          touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI}} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          cat .env
          ls

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: bakkym/haustierfash-web-backend:2.0.0

  Dockerizing-frontend:
    runs-on: ubuntu-latest
    environment:
      name: Versions
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: bakkym/haustierfash-web-frontend:2.0.0
