name: Versions

on:
  push:
    branches: [release]
  workflow_dispatch:
      
jobs:
  Dockerizing:
    runs-on: ubuntu-latest
    environment:
      name: Versions
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Create env file'
        working-directory: ./backend
        run: |
          touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI}} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build docker images
        run: sudo docker-compose build

      - 
        name: Push images to DockerHub
        run: sudo docker-compose push


